### ISSUE TITLE
v7 Icons

### ISSUE THREAD

**Issue by mike-w-kelly** [dev-mag/uFluent#13]
In v7 the icons are now classes that use the icomoon font icons. 

However the v6 icon code doesn't appear to work

```
var homepageDocType = DocumentType.Get("Homepage");

homepageDocType.SetIcon("icon-truck");
```

Can you add support for v7 icons.

**Comment by anD1332** [comment]
I've tested this and you have to add the additional colour class e.g. color-red, color-black etc.

It is also possible to add icons as in v6 but they aren't shown in the document type settings, it shows that the icon hasn't been set but they are visible in the content tree.
