### ISSUE TITLE
Dependency Holding me back

### ISSUE THREAD

**Issue by Myster** [dev-mag/uFluent#15]
Hi,
I want to upgrade umbraco but I cannot.
Update-Package : Updating 'UmbracoCms.Core 7.2.1' to 'UmbracoCms.Core 7.2.2' failed. Unable to find a version of 'uFluent' that is compatible with 'UmbracoC
ms.Core 7.2.2'.

It seems to me a little 'looser' dependency requirement would be better. 
It seems like this strict dependency is a serious reason to decide against using uFluent in that I can't apply upgrades (security or otherwise) in a timely manner. (I suppose I could fork it but I'd rather not ;-)

Umbraco should follow sem. ver. if they don't it's not your fault. :-)

**Comment by tgriley** [comment]
True, that might be a bit of a harsh dependency. We'll reduce its specificity shortly.

**Comment by tgriley** [comment]
Fixed in commit 29812846de63df8a1c079d588293baf4c57cb10b.
