### ISSUE TITLE
Set Datatype by name rather than GUID.

### ISSUE THREAD

**Issue by Myster** [dev-mag/uFluent#16]
I'd like to do the following rather than having to find the guid for the controlId

```
DataType.Get("Article Multi Picker")
        .SetControlId("Umbraco.MultiNodeTreePicker")
```

**Comment by tgriley** [comment]
You can use the uFluent.Consts.PropertyEditor consts class for the standard editors, I've just tested it locally and seems to work fine. Maybe we should rename that SetControlId to SetPropertyEditor.... :S

**Comment by katerd** [comment]
This is now possible in uFluent 7.0.6 e,g.:

```
DataType
    .Get("Link Picker")
    .SetPropertyEditor("Gibe.LinkPicker")
    .Save();
```
