### ISSUE TITLE
Document Type property sorting

### ISSUE THREAD

**Issue by anD1332** [dev-mag/uFluent#19]
At the moment properties are shown in the order that they was added to the doctype.  This is an enhancement to be able to sort properties via a migration.

Example migration to look like:

```
DocumentType.Get("Homepage")
            .SetPropertySortOrder("title", 0)
            .SetPropertySortOrder("heroImage", 1)
            .Save();
```

**Comment by kiasyn** [comment]
Created a pull request to add this functionality - https://github.com/dev-mag/uFluent/pull/27

**Comment by anD1332** [comment]
Merged and published to nuget.]

Thank you for your contribution!
