### ISSUE TITLE
Template.Get returning null.

### ISSUE THREAD

**Issue by eriksimonic** [dev-mag/uFluent#25]
Hi.

When I use Template.Get('templatename') I always get NULL. But I triple check if the template is defined as it should be. 

Thanks.

**Comment by tgriley** [comment]
Hey, we'll take a look. Are you running Umbraco 6 or 7?

**Comment by eriksimonic** [comment]
I  currently running 7.4.2 but the same was with 7.3.x

**Comment by tgriley** [comment]
I cant replicate it against Umbraco 7.2. Ill fire up a new one with 7.4 and give it another go later.

**Comment by eriksimonic** [comment]
I think i found where is the problem.

In Umbraco 7.4 the Umbraco.Core.Models.Template.

the MasterTemplateAlias is now Public but in the SetMasterTemplate is used dome reflection to get the property with NonPublic flag.

 type.GetProperty("MasterTemplateAlias", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(this.UmbracoTemplate, masterTemplate.Alias, null);
            PropertyInfo property = type.GetProperty("MasterTemplateId", BindingFlags.NonPublic | BindingFlags.Instance);

Fixing that should fix the problem.

My problem was not finding the template but setting the parent for it, but since it was writen in an expressive way I was stered to thing that the template is missing.

**Comment by anD1332** [comment]
This has been released under a new branch umbraco-7.4.2 and has been published to nuget version 7.4.2.2
