### ISSUE TITLE
Demo Umbraco 7 installation w/ migrations

### ISSUE THREAD

**Issue by katerd** [dev-mag/uFluent#4]
- [x] Text string property.
- [ ] Create URL picker.
- [x] Create multi-node tree picker.
- [x] Create doctype.
  - [x] Default template.
  - [x] Create property set to mandatory.
  - [x] Create tab.
  - [x] Move property to new tab.
- [x] Create 3 templates.
- [x] Set master template.
- [x] Delete unused template.

**Comment by anD1332** [comment]
Sample project has been created using Umbraco 7 with migrations listed above.  Umbraco 7 has changed the URL picker to "Multi URL Picker"; raised this as a separate issue
