### ISSUE TITLE
Data Types - Multinode Tree Picker

### ISSUE THREAD

**Issue by mike-w-kelly** [dev-mag/uFluent#5]
I'm currently working on a project that is using the [Local Gov Start Kit](http://our.umbraco.org/projects/starter-kits/localgov-starter-kit), which has a few data types not supported by uFluent
## Multinode Treepicker : Umbraco.MultiNodeTreePicker

The starter kit uses the Multinode Treepicker within a custom data type called ulg.ServiceAlert

![ulg servicealert](https://cloud.githubusercontent.com/assets/10595930/5799150/cf65d440-9fc6-11e4-97a3-e69ac528a24d.PNG)

The Multinode tree picker doesn't appear to be implemented as standard data type so I'm assuming I can't use it as a custom one.

**Comment by anD1332** [comment]
Hi Mike, 

This has been released now and MNTPs can be created in a migration similar to the following:

```
DataType.Create(CustomDataTypeConsts.UsefulLinksPicker, PropertyEditor.MultiNodeTreePicker)
                .SetMultiNodeTreePickerPreValues(new MultiNodeTreePickerPreValues(NodeType.Content, null, null, "Homepage", 1, null, false))
                .Save();
```

If you have any further questions surrounding this data type or face any issues please get in touch.

Thanks
Andy
