### ISSUE TITLE
Data Types - List Views

### ISSUE THREAD

**Issue by mike-w-kelly** [dev-mag/uFluent#6]
The new List View data types introduced in Umbraco 7
- List View - Content
- List View - Media
- List View - Members

Any plans on when this will be added? It's not an urgent requirement for the moment, but as it's a built in data type it would be nice to be able to use it code first.

**Comment by tgriley** [comment]
Labeling as bug as all default umbraco stuff should be supported.

**Comment by katerd** [comment]
These have now been added into uFluent 7.0.6
