### ISSUE TITLE
Data Types - Tags as Custom Data Type

### ISSUE THREAD

**Issue by mike-w-kelly** [dev-mag/uFluent#7]
I'm currently working on a project that is using the [Local Gov Start Kit](http://our.umbraco.org/projects/starter-kits/localgov-starter-kit), which has a few data types not supported by uFluent
## Tags : Umbraco.Tags

The starter kit uses Tags within a custom data type  called ulg.AZTags

![ulg aztags](https://cloud.githubusercontent.com/assets/10595930/5799267/50430e92-9fc8-11e4-9886-1df9062981cf.PNG)

Speaking to Tom last week he said the ability to use Tags as a custom data type hadn't yet been implemented.

**Comment by anD1332** [comment]
This will hopefully be released soon.

**Comment by anD1332** [comment]
This was released in May
